/** Protected application routes */
export const PATH_HOME = '/';
export const PATH_TEAMS = '/teams';
export const PATH_TODOS = '/todos';
export const PATH_AGENDA = '/agenda';
export const PATH_NOTES = '/notes';
export const PATH_UTILITIES_DOCUMENT = '/utilities/document';
export const PATH_UTILITIES_STRUCTURED = '/utilities/structured';
export const PATH_PLANNING = '/planning';
export const PATH_ANALYTICS = '/analytics';
export const PATH_ANALYTICS_ACTIVITY = '/analytics/activity';
export const PATH_PROFILE = '/profile';
export const PATH_SETTINGS = '/settings';
export const PATH_GUIDE = '/guide';
export const PATH_LOGIN = '/login';
export const PATH_REGISTER = '/register';
